const PHOTOS=[{src:"assets/images/photo-01.jpg",category:"Ganesh Ji",title:"गणेश जी मूर्ति दर्शन"},{src:"assets/images/photo-02.jpg",category:"Puja",title:"प्राण प्रतिष्ठा पूजा"},{src:"assets/images/photo-03.jpg",category:"Decoration",title:"मंडप सजावट 2025"},{src:"assets/images/photo-04.jpg",category:"Cultural Program",title:"सांस्कृतिक कार्यक्रम"},{src:"assets/images/photo-05.jpg",category:"Visarjan",title:"विसर्जन शोभा यात्रा"},{src:"assets/images/photo-06.jpg",category:"Ganesh Ji",title:"श्री गणेश दर्शन"}];
const VIDEOS=[{src:"assets/videos/video-01.mp4",thumb:"assets/images/photo-01.jpg",category:"Puja Videos",title:"स्थापना पूजा"},{src:"assets/videos/video-02.mp4",thumb:"assets/images/photo-02.jpg",category:"Aarti",title:"गणेश आरती"},{src:"assets/videos/video-03.mp4",thumb:"assets/images/photo-03.jpg",category:"Cultural Program",title:"सांस्कृतिक नृत्य"}];
document.addEventListener('DOMContentLoaded',()=>{
const ham=document.getElementById('hamburger'),nav=document.getElementById('navLinks');if(ham)ham.addEventListener('click',()=>nav.classList.toggle('open'));
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lbImg'),lbCap=document.getElementById('lbCaption'),lbClose=document.getElementById('lbClose');
function openLB(s,c){if(!lb)return;lbImg.src=s;lbCap.textContent=c;lb.classList.add('active')}function closeLB(){lb.classList.remove('active')}
if(lbClose)lbClose.addEventListener('click',closeLB);if(lb)lb.addEventListener('click',e=>{if(e.target===lb)closeLB()});
const hp=document.getElementById('homePhotos');if(hp){PHOTOS.slice(0,6).forEach(p=>{hp.innerHTML+=`<div class="card" data-src="${p.src}" data-title="${p.title}"><img src="${p.src}" alt="${p.title}" onerror="this.src='https://via.placeholder.com/600x400/FF6F00/fff?text=${p.title}'"><div class="card-body"><h4>${p.title}</h4><span>${p.category}</span></div></div>`});hp.querySelectorAll('.card').forEach(c=>c.addEventListener('click',()=>openLB(c.dataset.src,c.dataset.title)))}
const hv=document.getElementById('homeVideos');if(hv){VIDEOS.slice(0,3).forEach(v=>{hv.innerHTML+=`<div class="video-card"><video src="${v.src}" controls poster="${v.thumb}"></video><div class="card-body"><h4>${v.title}</h4></div></div>`})}
const pg=document.getElementById('photoGrid');if(pg){function renderP(f){pg.innerHTML='';const list=f==='all'?PHOTOS:PHOTOS.filter(p=>p.category===f);list.forEach(p=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<img src="${p.src}" alt="${p.title}" onerror="this.src='https://via.placeholder.com/600x400/FF6F00/fff?text=${p.title}'"><div class="card-body"><h4>${p.title}</h4><span>${p.category}</span></div>`;d.addEventListener('click',()=>openLB(p.src,p.title));pg.appendChild(d)})}renderP('all');document.querySelectorAll('#photoFilters .filter-btn').forEach(b=>{b.addEventListener('click',()=>{document.querySelectorAll('#photoFilters .filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderP(b.dataset.filter)})})}
const vg=document.getElementById('videoGrid');if(vg){function renderV(f){vg.innerHTML='';const list=f==='all'?VIDEOS:VIDEOS.filter(v=>v.category===f);list.forEach(v=>{const d=document.createElement('div');d.className='video-card';d.innerHTML=`<video src="${v.src}" controls poster="${v.thumb}"></video><div class="card-body"><h4>${v.title}</h4><span>${v.category}</span></div>`;vg.appendChild(d)})}renderV('all');document.querySelectorAll('#videoFilters .filter-btn').forEach(b=>{b.addEventListener('click',()=>{document.querySelectorAll('#videoFilters .filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderV(b.dataset.filter)})})}
});